:construction_worker: Fixes CI build
Error was:
```
make: python3.8: Command not found
python3.8 -m venv venv
make: *** [venv] Error 127
Makefile:23: recipe for target 'venv' failed
Error: Process completed with exit code 2.
```
Also fixes `isort` warnings, the error was:
```
UserWarning: W0501:
The following deprecated CLI flags were used and ignored: --recursive
```
And updates `black` linting.